---
title: "Title"
author: "Daniel DeFoe"
output: html_document
---

Note:  This should be written in article style - i.e., use "we" not "I".  Do not try to be overly formal, but of course, do use complete sentences and proper grammar.

Brevity is good!  Think about what your main takeaway message is of each subsection, and stick to it.   (You are already very good at this!)

Lots of plots and figures is fine; but again, better to have one plot that tells a clear story than many plots that need to be understood together.

I vaguely expect this to be around 5 pages - however, it may be much longer if you include many plots/tables/lists, and that's completely okay!

## Abstract

One longish paragraph summarizing the contributions of this paper. Good advice for abstract writing can be found here: https://writingcenter.gmu.edu/guides/writing-an-abstract

## Introduction

[Consider the Abstract to be a standalone, separate from the paper, not as the first section.  The Introduction should start from scratch. It is okay if the Introduction feels like a bit of a repeat of parts of the abstract - don't copy word for word, but don't worry about repeating yourself.]

1-3 paragraphs introducing the project.  The way you have done this for the Maroon 5 writeup is perfect; emulate that style!  This would also be a good place to reference - and perhaps even pull a quote from - the Song Factory book and/or any other articles you've come across.


### Data Collection

Briefly describe the data sources and collection process.  Feel free to use bullet point lists (in limited capacity) to show which information was pulled from which website.

Omit details of the scraping process itself, but do include limitations and judgement calls.  For example, you should mention the issue of tossing out live or re-release versions of songs.

Make sure you reference Charlie's work here.

## Quantifying a song

3-4 sentences stating the challenge of converting a song to a quantifiable measure.

### Popularity

Discussion of the popularity metrics.  For *each* metric, I would like to see:
* A "layman's terms" description (as you have done very nicely in the Maroon 5 writeup)
* A formal equation
* A very brief explanation of the equation  (e.g., "we take the log of the Billboard rank to induce a more gradual drop-off, as we do not believe rank 1 is twice as significant as rank 2")
* A plot (boxplot or histogram) showing the distribution of scores across songs.  Either use Maroon 5 songs as your example, or include all songs in your archetypal artists - but do NOT standardize for this plot!  

Discuss briefly the relationships between popularity metrics.  This can be short - just observe that 1&2 capture a similar thing, 3&4 capture a similar thing.

Conclude that we like your invented measure best. Justify this briefly.

### Complexity

Same as above.  Feel free to also include more discussion of the various sub-measures that are combined into your total Lyrical measure and Musical measure.  

## Case Study: Maroon 5

Here you can essentially copy-paste your Buzzfeed article, but pare it down a bit to which takeaway messages seem to fit best in your overall writeup.

## Artist Archetypes

We'll discuss this on Tuesday

## Conclusions

A medium paragraph restating all the takeaway messages.

## Future Work

Talk about the various directions of research this work could lead to.  This is where you can solidify all your great ideas!  Most of them won't fit into a Senior Project, but it will be great to propose them all here.

## References
